
import { MockeryAction } from "@/types/mockery-types";

// Full descriptions for all mockery actions
export const mockeryDescriptions: Record<MockeryAction, string> = {
  tomato: "Throw a tomato at the user",
  egg: "Throw an egg at the user",
  rotten_egg: "Throw a rotten egg for extra stench",
  flame: "Flame the user in public",
  heart: "Ironically heart their profile",
  thumbs_down: "Show disapproval",
  skull: "Mark them as digitally deceased",
  crown: "Crown them as the fool",
  putridEgg: "A specialty item that really stinks",
  stocks: "Place them in the digital stocks for public mockery",
  jester: "Declare them the court jester",
  mock: "Simple mockery for simple folk",
  challenge: "Challenge them to prove their worth",
  joust: "Challenge them to a spending joust",
  duel: "Declare a spending duel",
  silence: "Temporarily silence them",
  laugh: "Publicly laugh at their status",
  fish: "Slap them with a digital fish",
  taunt: "Taunt them mercilessly",
  thumbsDown: "Express your disapproval",
  trumpet: "Announce their failure",
  confetti: "Ironically celebrate their spending",
  shame: "Publicly shame them",
  courtJester: "Name them the court's fool",
  smokeBomb: "Leave them in a cloud of confusion",
  protection: "Protect yourself from their mockery",
  royal_decree: "Issue a royal decree of shame",
  shame_certificate: "Award a certificate of shame",
  insult: "Deliver a royal insult",
  humiliate: "Publicly humiliate them"
};

// Short descriptions for mockery action tooltips
export const mockeryShortDescriptions: Record<MockeryAction, string> = {
  tomato: "Throw a tomato",
  egg: "Throw an egg",
  rotten_egg: "Throw a rotten egg",
  flame: "Flame publicly",
  heart: "Ironically heart",
  thumbs_down: "Show disapproval",
  skull: "Mark as deceased",
  crown: "Crown as fool",
  putridEgg: "Throw putrid egg",
  stocks: "Put in stocks",
  jester: "Name as jester",
  mock: "Simple mockery",
  challenge: "Challenge worth",
  joust: "Spending joust",
  duel: "Spending duel",
  silence: "Temporary silence",
  laugh: "Public laughter",
  fish: "Slap with fish",
  taunt: "Merciless taunt",
  thumbsDown: "Disapproval",
  trumpet: "Announce failure",
  confetti: "Ironic celebration",
  shame: "Public shame",
  courtJester: "Court fool",
  smokeBomb: "Confusion cloud",
  protection: "Self-protection",
  royal_decree: "Royal shame decree",
  shame_certificate: "Shame certificate",
  insult: "Royal insult",
  humiliate: "Public humiliation"
};
