
import { MockeryAction, MockeryTier } from '@/types/mockery';

// Get display title for a mockery action
export const getMockeryActionTitle = (action: MockeryAction): string => {
  const titles: Record<string, string> = {
    tomatoes: 'Rotten Tomatoes',
    eggs: 'Egg Attack',
    stocks: 'The Stocks',
    crown: 'False Crown',
    dragon: 'Dragon Mockery',
    demon: 'Demonic Insult',
    dunce: 'Dunce Cap',
    jester: 'Court Jester',
    troll: 'Internet Troll',
    peasant: 'Peasant Status',
    rat: 'Royal Rat',
    skeleton: 'Skeleton Frame',
    zombie: 'Zombie Effect',
    witch: 'Witch Hex',
    monster: 'Monster Mask',
    knight: 'Fallen Knight',
    bishop: 'Corrupt Bishop',
    rook: 'Fallen Rook',
    pawn: 'Mere Pawn',
    king: 'False King',
    queen: 'False Queen',
    ghost: 'Ghost Effect',
    target: 'Target Mark',
    challenge: 'Royal Challenge',
    immune: 'Immunity',
    shame: 'Public Shame',
    protection: 'Royal Protection',
    putridEggs: 'Putrid Eggs',
    silence: 'Silence Decree',
    courtJester: 'Court Jester',
    jest: 'Royal Jest',
    smokeBomb: 'Smoke Bomb',
    glitterBomb: 'Glitter Bomb',
    royalPie: 'Royal Pie',
    jokeCrown: 'Joke Crown',
    memeFrame: 'Meme Frame',
    roast: 'Royal Roast',
    ridicule: 'Public Ridicule',
    humiliate: 'Royal Humiliation',
    expose: 'Public Exposure',
    mock: 'Mock Royalty',
    taunt: 'Royal Taunt',
    guillotine: 'The Guillotine',
    defeat: 'Royal Defeat',
    removal: 'Royal Removal',
    dungeons: 'Royal Dungeons',
    fool: 'Royal Fool'
  };
  
  return titles[action] || 'Unknown Mockery';
};

// Get description for a mockery action
export const getMockeryActionDescription = (action: MockeryAction): string => {
  const descriptions: Record<string, string> = {
    tomatoes: 'Pelt the user with virtual rotten tomatoes, leaving a messy splatter effect.',
    eggs: 'Throw eggs at the user, displaying a humorous broken egg effect.',
    stocks: 'Lock the user in the public stocks for all to mock.',
    crown: 'Place a ridiculous crown on their head to mock their achievements.',
    dragon: 'Unleash a dragon\'s mockery upon the user.',
    demon: 'Subject the user to demonic ridicule.',
    dunce: 'Place a dunce cap on their head.',
    jester: 'Turn the user into the court jester.',
    troll: 'Mark the user as an internet troll.',
    peasant: 'Reduce the user to peasant status.',
    rat: 'Compare the user to a royal rat.',
    skeleton: 'Give the user a skeleton frame effect.',
    zombie: 'Turn the user into a zombie.',
    witch: 'Cast a witch hex on the user.',
    monster: 'Make the user appear as a monster.',
    knight: 'Demote the user to a fallen knight.',
    bishop: 'Mark the user as a corrupt bishop.',
    rook: 'Demote the user to a fallen rook.',
    pawn: 'Demote the user to a mere pawn.',
    king: 'Mock the user with a false king title.',
    queen: 'Mock the user with a false queen title.',
    ghost: 'Make the user appear as a ghost.',
    target: 'Mark the user as a target for mockery.',
    challenge: 'Issue a royal challenge to the user.',
    immune: 'Grant immunity from mockery.',
    shame: 'Subject the user to public shame.',
    protection: 'Protect the user from mockery with royal protection.',
    putridEggs: 'Throw putrid eggs at the user for an even more humiliating effect.',
    silence: 'Silence the user with a royal decree.',
    courtJester: 'Promote the user to court jester for maximum mockery.',
    jest: 'Make a royal jest at the user\'s expense.',
    smokeBomb: 'Deploy a smoke bomb to obscure the user in smoke.',
    glitterBomb: 'Throw a glitter bomb at the user for a sparkly humiliation.',
    royalPie: 'Throw a royal pie at the user\'s face.',
    jokeCrown: 'Place a joke crown on the user\'s head.',
    memeFrame: 'Frame the user in a humorous meme.',
    roast: 'Deliver a royal roast to the user.',
    ridicule: 'Subject the user to public ridicule.',
    humiliate: 'Royally humiliate the user.',
    expose: 'Expose the user\'s follies to the public.',
    mock: 'Mock the user\'s royal aspirations.',
    taunt: 'Deliver a royal taunt to the user.',
    guillotine: 'Subject the user to a virtual guillotine.',
    defeat: 'Mark the user as royally defeated.',
    removal: 'Remove the user from royal consideration.',
    dungeons: 'Send the user to the royal dungeons.',
    fool: 'Make the user look like a royal fool.'
  };
  
  return descriptions[action] || 'An unknown form of mockery';
};

// Get the price of a mockery action
export const getMockeryActionPrice = (action: MockeryAction): number => {
  const prices: Record<string, number> = {
    tomatoes: 0.25,
    eggs: 0.50,
    stocks: 1.00,
    crown: 2.00,
    dragon: 5.00,
    demon: 4.00,
    dunce: 0.75,
    jester: 1.50,
    troll: 1.25,
    peasant: 0.50,
    rat: 0.50,
    skeleton: 1.00,
    zombie: 1.50,
    witch: 1.75,
    monster: 2.00,
    knight: 1.25,
    bishop: 1.50,
    rook: 1.25,
    pawn: 0.50,
    king: 3.00,
    queen: 3.00,
    ghost: 1.00,
    target: 1.00,
    challenge: 2.00,
    immune: 5.00,
    shame: 0.25,
    protection: 10.00,
    putridEggs: 0.75,
    silence: 2.50,
    courtJester: 2.00,
    jest: 1.00,
    smokeBomb: 1.50,
    glitterBomb: 1.75,
    royalPie: 1.25,
    jokeCrown: 2.00,
    memeFrame: 1.50,
    roast: 1.00,
    ridicule: 1.50,
    humiliate: 2.50,
    expose: 3.00,
    mock: 1.00,
    taunt: 1.25,
    guillotine: 3.50,
    defeat: 2.00,
    removal: 5.00,
    dungeons: 4.00,
    fool: 0.75
  };
  
  return prices[action] || 0.25;
};

// Get the tier of a mockery action
export const getMockeryTier = (action: MockeryAction): MockeryTier => {
  const tiers: Record<string, MockeryTier> = {
    tomatoes: 'basic',
    eggs: 'basic',
    stocks: 'premium',
    crown: 'premium',
    dragon: 'legendary',
    demon: 'epic',
    dunce: 'basic',
    jester: 'premium',
    troll: 'premium',
    peasant: 'basic',
    rat: 'basic',
    skeleton: 'premium',
    zombie: 'premium',
    witch: 'epic',
    monster: 'epic',
    knight: 'premium',
    bishop: 'premium',
    rook: 'premium',
    pawn: 'basic',
    king: 'royal',
    queen: 'royal',
    ghost: 'premium',
    target: 'basic',
    challenge: 'royal',
    immune: 'legendary',
    shame: 'basic',
    protection: 'legendary',
    putridEggs: 'premium',
    silence: 'royal',
    courtJester: 'epic',
    jest: 'premium',
    smokeBomb: 'premium',
    glitterBomb: 'epic',
    royalPie: 'premium',
    jokeCrown: 'epic',
    memeFrame: 'premium',
    roast: 'basic',
    ridicule: 'premium',
    humiliate: 'epic',
    expose: 'royal',
    mock: 'basic',
    taunt: 'premium',
    guillotine: 'royal',
    defeat: 'epic',
    removal: 'legendary',
    dungeons: 'royal',
    fool: 'basic'
  };
  
  return tiers[action] || 'basic';
};
