
// Function to adapt icon names from various sources to a standardized format
export function adaptIconName(iconName: string): string {
  // Convert to lowercase and remove spaces
  const lowercased = iconName.toLowerCase().replace(/\s+/g, '');
  
  // Check special cases first 
  if (specialCaseMap[lowercased]) {
    return specialCaseMap[lowercased];
  }
  
  // Remove common prefixes/suffixes
  let sanitized = lowercased
    .replace(/^icon/i, '')
    .replace(/icon$/i, '')
    .replace(/^fa-/i, '')
    .replace(/^fa/i, '');
    
  // Return the sanitized icon name or a fallback if it's too short
  return sanitized.length > 1 ? sanitized : 'question';
}

// Map of special case icon names
const specialCaseMap: Record<string, string> = {
  // Social media
  'facebook': 'facebook',
  'fb': 'facebook',
  'twitter': 'twitter',
  'x': 'twitter',
  'instagram': 'instagram',
  'insta': 'instagram',
  'linkedin': 'linkedin',
  'github': 'github',
  'youtube': 'youtube',
  'tiktok': 'tiktok',
  'discord': 'discord',
  'twitch': 'twitch',
  'pinterest': 'pinterest',
  'snapchat': 'snapchat',
  'telegram': 'telegram',
  'whatsapp': 'whatsapp',
  'reddit': 'reddit',
  'medium': 'medium',
  'behance': 'behance',
  'dribbble': 'dribbble',
  'vimeo': 'vimeo',
  'slack': 'slack',
  
  // Common UI icons
  'home': 'home',
  'user': 'user',
  'users': 'users',
  'settings': 'settings',
  'gear': 'settings',
  'cog': 'settings',
  'cogwheel': 'settings',
  'profile': 'user',
  'account': 'user',
  'person': 'user',
  'mail': 'mail',
  'email': 'mail',
  'message': 'mail',
  'envelope': 'mail',
  'notification': 'bell',
  'notifications': 'bell',
  'alert': 'bell',
  'alerts': 'bell',
  'search': 'search',
  'find': 'search',
  'magnify': 'search',
  'calendar': 'calendar',
  'date': 'calendar',
  'time': 'clock',
  'clock': 'clock',
  'schedule': 'calendar',
  'location': 'map-pin',
  'pin': 'map-pin',
  'place': 'map-pin',
  'marker': 'map-pin',
  'address': 'map-pin',
  'phone': 'phone',
  'call': 'phone',
  'telephone': 'phone',
  'lock': 'lock',
  'unlock': 'unlock',
  'secure': 'lock',
  'logout': 'log-out',
  'signout': 'log-out',
  'login': 'log-in',
  'signin': 'log-in',
  'heart': 'heart',
  'like': 'heart',
  'favorite': 'heart',
  'star': 'star',
  'rating': 'star',
  'bookmark': 'bookmark',
  'save': 'bookmark',
  'edit': 'edit',
  'pencil': 'edit',
  'modify': 'edit',
  'delete': 'trash',
  'trash': 'trash',
  'remove': 'trash',
  'bin': 'trash',
  'add': 'plus',
  'plus': 'plus',
  'create': 'plus',
  'new': 'plus',
  'subtract': 'minus',
  'minus': 'minus',
  'remove-item': 'minus',
  'loading': 'loader',
  'spinner': 'loader',
  'refresh': 'refresh-cw',
  'reload': 'refresh-cw',
  'share': 'share',
  'upload': 'upload',
  'download': 'download',
  'copy': 'copy',
  'duplicate': 'copy',
  'menu': 'menu',
  'hamburger': 'menu',
  'more': 'more-horizontal',
  'more-horizontal': 'more-horizontal',
  'more-vertical': 'more-vertical',
  'dots': 'more-horizontal',
  'ellipsis': 'more-horizontal',
  'options': 'more-horizontal',
  'info': 'info',
  'information': 'info',
  'help': 'help-circle',
  'question': 'help-circle',
  'faq': 'help-circle',
  'warning': 'alert-triangle',
  'alert-triangle': 'alert-triangle',
  'error': 'alert-circle',
  'alert-circle': 'alert-circle',
  'success': 'check-circle',
  'check-circle': 'check-circle',
  'close': 'x',
  'cancel': 'x',
  'x': 'x',
  'check': 'check',
  'tick': 'check',
  'complete': 'check',
  'arrow-up': 'arrow-up',
  'arrow-right': 'arrow-right',
  'arrow-down': 'arrow-down',
  'arrow-left': 'arrow-left',
  'chevron-up': 'chevron-up',
  'chevron-right': 'chevron-right',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  
  // Medieval and royal themed icons
  'crown': 'crown',
  'king': 'crown',
  'queen': 'crown',
  'royal': 'crown',
  'shield': 'shield',
  'protect': 'shield',
  'defense': 'shield',
  'sword': 'sword',
  'attack': 'sword',
  'weapon': 'sword',
  'treasure': 'gift',
  'gift': 'gift',
  'present': 'gift',
  'reward': 'gift',
  'castle': 'home',
  'fortress': 'home',
  'palace': 'home',
  'scroll': 'scroll',
  'parchment': 'scroll',
  'document': 'file-text',
  'file': 'file',
  'certificate': 'award',
  'award': 'award',
  'medal': 'award',
  'achievement': 'award',
  'trophy': 'trophy',
  'win': 'trophy',
  'victory': 'trophy',
  'coins': 'dollar-sign',
  'money': 'dollar-sign',
  'currency': 'dollar-sign',
  'gold': 'dollar-sign',
  'wealth': 'dollar-sign',
  'horse': 'compass',
  'journey': 'compass',
  'compass': 'compass',
  'navigation': 'compass',
  'map': 'map',
  'route': 'map',
  'flask': 'flask',
  'potion': 'flask',
  'alchemy': 'flask',
  'feather': 'feather',
  'quill': 'feather',
  'write': 'feather',
  'flame': 'flame',
  'fire': 'flame',
  'torch': 'flame',
  'moon': 'moon',
  'night': 'moon',
  'sun': 'sun',
  'day': 'sun',
  'eye': 'eye',
  'view': 'eye',
  'visibility': 'eye',
  'eyeclosed': 'eye-off',
  'eyeoff': 'eye-off',
  'hidden': 'eye-off',
  'target': 'target',
  'aim': 'target',
  'goal': 'target',
  'bell': 'bell',
  'notification': 'bell',
  'alert': 'bell'
};

export default adaptIconName;
