
import { User } from '@/types/user';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'RoyalTycoon',
    email: 'royal@example.com',
    displayName: 'Royal Tycoon',
    profileImage: 'https://randomuser.me/api/portraits/men/1.jpg',
    bio: 'The undisputed king of spending! Bow before my wealth!',
    tier: 'royal',
    role: 'user',
    team: 'Red',
    rank: 1,
    walletBalance: 1500.50,
    walletAddress: 'BW1Y9SqiPRSsEDxoYfSrpHpnvWNKGrNHyBnb4HqQiwJP',
    totalSpent: 9850.25,
    spentAmount: 9850.25,
    amountSpent: 9850.25,
    joinDate: '2023-01-15T12:00:00Z',
    createdAt: '2023-01-15T12:00:00Z',
    updatedAt: '2023-03-20T14:30:00Z',
    isVerified: true,
    cosmetics: {
      borders: ['royal-border-1', 'royal-border-2'],
      colors: ['royal-color-1'],
      fonts: ['royal-font-1'],
      emojis: ['royal-emoji-1', 'royal-emoji-2'],
      titles: ['royal-whale', 'money-monarch'],
      backgrounds: ['royal-bg-1'],
      effects: ['royal-effect-1'],
      badges: ['royal-badge-1', 'royal-badge-2'],
      themes: ['royal-theme-1'],
      activeBorder: 'royal-border-1',
      activeColor: 'royal-color-1',
      activeFont: 'royal-font-1',
      activeEmoji: 'royal-emoji-1',
      activeTitle: 'money-monarch',
      activeBackground: 'royal-bg-1',
      activeEffect: 'royal-effect-1',
      activeBadge: 'royal-badge-1',
      activeTheme: 'royal-theme-1'
    },
    subscription: {
      tier: 'royal',
      startDate: '2023-01-20T00:00:00Z',
      endDate: '2024-01-20T00:00:00Z',
      isActive: true,
      features: ['profile_customization', 'mockery_immunity', 'exclusive_items']
    },
    activeTitle: 'money-monarch',
    socialLinks: {
      twitter: 'https://twitter.com/royaltycoon',
      instagram: 'https://instagram.com/royaltycoon'
    }
  },
  {
    id: 'user-2',
    username: 'WealthFlex',
    email: 'wealth@example.com',
    displayName: 'Wealth Flex',
    profileImage: 'https://randomuser.me/api/portraits/women/2.jpg',
    bio: 'Flaunting my wealth is just what I do best.',
    tier: 'platinum',
    role: 'user',
    team: 'Blue',
    rank: 2,
    walletBalance: 850.75,
    totalSpent: 7342.18,
    spentAmount: 7342.18,
    amountSpent: 7342.18,
    joinDate: '2023-02-01T10:15:00Z',
    createdAt: '2023-02-01T10:15:00Z',
    updatedAt: '2023-03-18T09:20:00Z',
    isVerified: true,
    cosmetics: {
      borders: ['platinum-border-1'],
      colors: ['platinum-color-1'],
      fonts: ['platinum-font-1'],
      emojis: ['platinum-emoji-1'],
      titles: ['wealth-master'],
      backgrounds: ['platinum-bg-1'],
      effects: [],
      badges: ['platinum-badge-1'],
      themes: [],
      activeBorder: 'platinum-border-1',
      activeColor: 'platinum-color-1',
      activeFont: 'platinum-font-1',
      activeEmoji: 'platinum-emoji-1',
      activeTitle: 'wealth-master',
      activeBackground: 'platinum-bg-1',
      activeBadge: 'platinum-badge-1'
    },
    subscription: {
      tier: 'platinum',
      startDate: '2023-02-05T00:00:00Z',
      endDate: '2024-02-05T00:00:00Z',
      isActive: true,
      features: ['profile_customization', 'mockery_immunity']
    },
    activeTitle: 'wealth-master'
  },
  {
    id: 'user-3',
    username: 'MoneyMaker',
    email: 'money@example.com',
    displayName: 'Money Maker',
    profileImage: 'https://randomuser.me/api/portraits/men/3.jpg',
    bio: 'Making money and spending it.',
    tier: 'gold',
    role: 'user',
    team: 'Green',
    rank: 3,
    walletBalance: 325.50,
    totalSpent: 5678.90,
    spentAmount: 5678.90,
    amountSpent: 5678.90,
    joinDate: '2023-02-10T14:30:00Z',
    createdAt: '2023-02-10T14:30:00Z',
    updatedAt: '2023-03-15T11:45:00Z',
    isVerified: true,
    cosmetics: {
      borders: ['gold-border-1'],
      colors: ['gold-color-1'],
      fonts: [],
      emojis: ['gold-emoji-1'],
      titles: ['money-master'],
      backgrounds: [],
      effects: [],
      badges: [],
      themes: [],
      activeBorder: 'gold-border-1',
      activeColor: 'gold-color-1',
      activeEmoji: 'gold-emoji-1',
      activeTitle: 'money-master'
    },
    subscription: {
      tier: 'gold',
      startDate: '2023-02-15T00:00:00Z',
      endDate: '2024-02-15T00:00:00Z',
      isActive: true,
      features: ['profile_customization']
    },
    activeTitle: 'money-master'
  }
];

export default mockUsers;
