// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bukzshfxeldicnjbhpjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1a3pzaGZ4ZWxkaWNuamJocGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTg1MzMsImV4cCI6MjA1ODY5NDUzM30.yD7zwYkn7jjuh7-TaRaLtOvtbB7KP9P3TtnLU3bSwBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);